### ISSUE TITLE
Weird `Effect.forkScoped` behaviour when call it inside stream chain

### ISSUE THREAD

**Issue by dilame** [Effect-TS/effect#3187] opened 2024-07-06 01:02 UTC
### What version of Effect is running?

3.4.7

### What steps can reproduce the bug?

This test case terminates the upstream (logs `upstream finish` in the console), while it should not do this FMPOV.

https://effect.website/play#99a446c4f047

```ts
import { Chunk, Console, Effect, Fiber, PubSub, Schedule, Stream, Take } from "effect"

const program = Effect.gen(function*() {
  let fiber: Fiber.RuntimeFiber<void> | null = null
  let pubsub = yield* PubSub.unbounded<Take.Take<number>>()
  const sharedStream = Stream.fromSchedule(
    Schedule.spaced("1 seconds")
  ).pipe(
    Stream.tap((x) => Console.log("upstream tap", x)),
    Stream.ensuring(Console.log("uptream finished")),
    (self) =>
      Effect.gen(function*() {
        fiber ??= yield* Effect.forkScoped(
          Stream.runIntoPubSub(self, pubsub)
        )
        return Stream.fromPubSub(pubsub)
      }),
    Stream.unwrap,
    Stream.flattenTake
  )

  const first = yield* sharedStream.pipe(
    Stream.runHead,
  )
  console.log(first);
  yield* Effect.never
})

Effect.runPromise(Effect.scoped(program))
```

While this test case does pretty much the same thing, but in different place, works as expected

https://effect.website/play#9123f9fe986f

```ts
import { Console, Effect, PubSub, Schedule, Stream, Take } from "effect"

const program = Effect.gen(function* () {
  const stream = Stream.fromSchedule(Schedule.spaced("1 second")).pipe(
    Stream.tap((x) => Console.log("upstream tap", x)),
    Stream.ensuring(Console.log("uptream finished"))
  );
  const pubsub = yield* PubSub.unbounded<Take.Take<number>>();
  const sharedStream = Stream.fromPubSub(pubsub).pipe(Stream.flattenTake);
  yield* Effect.forkScoped(Stream.runIntoPubSub(stream, pubsub));

  const first = yield* sharedStream.pipe(
    Stream.take(1),
    Stream.tap((x) => Console.log("downstream tap", x)),
    Stream.ensuring(Console.log("downstream finish")),
    Stream.runHead
  );
  console.log(first);
  yield* Effect.never;
})

Effect.runPromise(Effect.scoped(program))
```

### Additional information

I need it for the `Stream.share` operator implementation https://github.com/Effect-TS/effect/pull/3080

**Comment by dilame** [comment] 2024-07-06 02:39
I figured out that `Stream.runCollect`/`Stream.runDrain` and others seems to silently provide the scope to stream. Because if write like this it works as expected
https://effect.website/play#2dcf318a5cd6

```ts
import { Chunk, Console, Effect, Fiber, PubSub, Schedule, Stream, Take } from "effect"

const program = Effect.gen(function*() {
  let fiber: Fiber.RuntimeFiber<void> | null = null
  let pubsub = yield* PubSub.unbounded<Take.Take<number>>()
  const sharedStream = Stream.fromSchedule(
    Schedule.spaced("1 seconds")
  ).pipe(
    Stream.tap((x) => Console.log("upstream tap", x)),
    Stream.ensuring(Console.log("uptream finished")),
    (self) =>
      Effect.gen(function*() {
        fiber ??= yield* Effect.forkScoped(
          Stream.runIntoPubSub(self, pubsub)
        )
        return Stream.fromPubSub(pubsub)
      }),
    Stream.unwrap,
    Stream.flattenTake
  )

  const first = yield* sharedStream.pipe(
    Stream.take(5),
    Stream.runForEachScoped((x) => Console.log(x))
  )
  console.log(first)
  yield* Effect.never
})

Effect.runPromise(Effect.scoped(program))
```

**Comment by dilame** [comment] 2024-07-06 02:50
The bug is here

https://github.com/Effect-TS/effect/blob/main/packages/effect/src/internal/channel/channelExecutor.ts#L1098

**Comment by mikearnaldi** [comment] 2024-07-06 06:11
Streams are materialized by consumption and they include a Scope. When a Stream is stopped no resources should leak, so the Scope should close. If you want explicit Scope management you should use runScoped but even when doing that you will be in an odd position as resources would be recreated when the stream is restarted. In pull based streams the stream exists only when it is consumed, in push based the stream exists as long as it is produced, our streams are pull based

**Comment by dilame** [comment] 2024-07-06 12:53
Isn't it a bug that `Stream.run` doesn't remove the scope from `R`?

**Comment by mikearnaldi** [comment] 2024-07-06 13:04
> Isn't it a bug that `Stream.run` doesn't remove the scope from `R`?

not necessarily as Scope shouldn't be in R, that said it could be added

**Comment by dilame** [comment] 2024-07-06 13:19
> not necessarily as Scope shouldn't be in R, that said it could be added

But if it provides the scope – shouldn't it be removed from `R`? 
Why Scope should not be in `R`? And if so, why do `Stream.runScoped` exists?

**Comment by mikearnaldi** [comment] 2024-07-06 13:35
runScoped exposes a Scope for the stream regardless of it's presence in R, you can almost consider it an internal which is exposed for some edge cases where you emit / return things that may outlive the stream's lifetime

**Comment by dilame** [comment] 2024-07-06 13:54
But why `Scope` shouldn't be in `R` of `Stream`? I see a valid use-cases for that.

I think not excluding `Scope` from the `R` when use `Stream.run*` makes me think that i have control over the Scope, because the program doesn't get compiled if i not provide the `Scope` by myself,  so i feel like i have a control. But actually the `Scope` that i provided and that was required by effect is not used here. It is a high-level API things, i think it is a valid expectation that if you are providing the scope at the edge of your program that is requested by just one part of your program – it will be connected one with another. 

And it looks like a bug that this `Scope` remains unused at all, because other parts of the program doesn't need a `Scope`, and that only one part that required it – created it's own `Scope` in the end after i provided mine. It even feels like betrayal:)

**Comment by mikearnaldi** [comment] 2024-07-06 14:32
> But why `Scope` shouldn't be in `R` of `Stream`? I see a valid use-cases for that.
> 
> I think not excluding `Scope` from the `R` when use `Stream.run*` makes me think that i have control over the Scope, because the program doesn't get compiled if i not provide the `Scope` by myself, so i feel like i have a control. But actually the `Scope` that i provided and that was required by effect is not used here. It is a high-level API things, i think it is a valid expectation that if you are providing the scope at the edge of your program that is requested by just one part of your program – it will be connected one with another.
> 
> And it looks like a bug that this `Scope` remains unused at all, because other parts of the program doesn't need a `Scope`, and that only one part that required it – created it's own `Scope` in the end after i provided mine. It even feels like betrayal:)

As explained already Streams already include a Scope, if you want another Scope use a separate service, if you want control of the Scope required to run a Stream you can use runScoped

**Comment by dilame** [comment] 2024-07-06 14:39
> As explained already Streams already include a Scope

Well, but how can i know that Streams already include a Scope if `Stream.run*` doesn't remove the `Scope` from Stream?

> if you want another Scope use a separate service

What do you mean by "separate service"?

> if you want control of the Scope required to run a Stream you can use runScoped

Do i understand you correctly, you are not saying that it is incorrect to have a `Stream<A, E, Scope>`, you just saying that it is incorrect to run such stream with `Stream.run()`?

**Comment by mikearnaldi** [comment] 2024-07-06 14:43
> > As explained already Streams already include a Scope
> 
> Well, but how can i know that Streams already include a Scope if `Stream.run*` doesn't remove the `Scope` from Stream?
> 
> > if you want another Scope use a separate service
> 
> What do you mean by "separate service"?
> 
> > if you want control of the Scope required to run a Stream you can use runScoped
> 
> Do i understand you correctly, you are not saying that it is incorrect to have a `Stream<A, E, Scope>`, you just saying that it is incorrect to run such stream with `Stream.run()`?

1. A Stream always requires a Scope to track resources allocated during its lifecycle.
2. No, I am saying it is incorrect to have `Stream<A, E, Scope>` as you should use Stream.scoped(effect) to lift Effect's that require a Scope into a Stream and that combinator removes the Scope from R of the Effect. If you want another Scope you should use `Stream<A, E, YourScope>`

**Comment by mikearnaldi** [comment] 2024-07-06 14:57
If you want to run a stream partially you can use `peel`

**Comment by dilame** [comment] 2024-07-06 14:57
> 1. A Stream always requires a Scope to track resources allocated during its lifecycle.

Now i know it from the source code of `channelExecutor` and this issue discussion, but i am just saying that it would be nice to know from the source code:) Current type declaration acts like stream could be ran with no scope, which i think a bug, because it leads to bugs in userland.



> No, I am saying it is incorrect to have `Stream<A, E, Scope>` as you should use Stream.scoped(effect) to lift Effect's that require a Scope into a Stream and that combinator removes the Scope from R of the Effect. If you want another Scope you should use `Stream<A, E, YourScope>`


This is the interesting part. Maybe i am missing something about scopes. What is `YourScope`? When i read the docs, i thought that it would be nice if effect had support for scopes in different dimensions. Is it some undocumented feature? Or i missed something?

**Comment by dilame** [comment] 2024-07-06 15:04
> I am saying it is incorrect to have Stream<A, E, Scope> as you should use Stream.scoped(effect) to lift Effect's that require a Scope into a Stream and that combinator removes the Scope from R of the Effect

I still don't understand why it is incorrect to have `Stream<A, E, Scope>`. 
I can clearly understand why `Stream.scoped(effect)` removes `Scope` from effect – because in just runs the provided effect internally with freshly created scope – just like it should. 
But i don't understand why it is incorrect to have `Stream<A, E, Scope>`. What's wrong with it?

**Comment by mikearnaldi** [comment] 2024-07-06 15:09
> > 1. A Stream always requires a Scope to track resources allocated during its lifecycle.
> 
> Now i know it from the source code of `channelExecutor` and this issue discussion, but i am just saying that it would be nice to know from the source code:) Current type declaration acts like stream could be ran with no scope, which i think a bug, because it leads to bugs in userland.
> 
> > No, I am saying it is incorrect to have `Stream<A, E, Scope>` as you should use Stream.scoped(effect) to lift Effect's that require a Scope into a Stream and that combinator removes the Scope from R of the Effect. If you want another Scope you should use `Stream<A, E, YourScope>`
> 
> This is the interesting part. Maybe i am missing something about scopes. What is `YourScope`? When i read the docs, i thought that it would be nice if effect had support for scopes in different dimensions. Is it some undocumented feature? Or i missed something?

A scope is just a service, you can have yours like:

```ts
import { Context, Effect, Scope } from "effect"

export class MyScope extends Context.Tag("MyScope")<MyScope, Scope.Scope>() {}

export const myScoped = <A, E, R>(effect: Effect.Effect<A, E, R>) =>
  Effect.acquireUseRelease(
    Scope.make(),
    (scope) => Effect.provideService(effect, MyScope, scope),
    (closeable, exit) => Scope.close(closeable, exit)
  )
```

**Comment by mikearnaldi** [comment] 2024-07-06 15:10
That said, yes, run should remove Scope from R, just for clarity

**Comment by dilame** [comment] 2024-07-06 15:20
> I am saying it is incorrect to have Stream<A, E, Scope>

It follows from this statement that it is incorrect to have `Effect.forkScoped` inside Stream chain, right?

Let's imagine the following situation: we have a WebSocket (or read from file, whatever), and we should run some long computation for each event. This computation should be continued even after the stream has finished.

```ts
import { Stream, Effect } from "effect";

declare const socket: Stream.Stream<number>;

const processNumber = (num: number) => Effect.sleep('1 hour');

const program = socket.pipe(
  Stream.tap(num =>  Effect.forkScoped(processNumber(num))),
  Stream.runDrain
);

Effect.runPromise(Effect.scoped(program))
```

In this case we have a `Stream<number, E, Scope>`. 
Is it an invalid approach?

**Comment by mikearnaldi** [comment] 2024-07-06 15:32
It should be:

```ts
import { Effect, Stream } from "effect"

declare const socket: Stream.Stream<number>

const processNumber = (num: number) => Effect.sleep("1 hour")

const program = socket.pipe(
  Stream.flatMap((num) => Stream.scoped(Effect.forkScoped(processNumber(num))).pipe(Stream.as(num))),
  Stream.runDrain
)

Effect.runPromise(program)
```

arguably `tap` should allow for a stream. If you want the above to expose a Scope and only take some elements you're looking for peeling the stream:

```ts
import { Chunk, Effect, Sink, Stream } from "effect"

declare const socket: Stream.Stream<number>

const processNumber = (num: number) => Effect.sleep("1 hour")

const stream = socket.pipe(
  Stream.flatMap((num) => Stream.scoped(Effect.forkScoped(processNumber(num))).pipe(Stream.as(num)))
)

const program = Effect.gen(function*() {
  let next = stream
  let elements: Chunk.Chunk<Stream.Stream.Success<typeof next>>

  while ([elements, next] = yield* Stream.peel(next, Sink.collectAllN(1)), Chunk.isNonEmpty(elements)) {
    yield* Effect.log(`elements: ${Chunk.toArray(elements)}`)
  }
})

Effect.runPromise(Effect.scoped(program))
```

**Comment by dilame** [comment] 2024-07-06 15:37
This code finishes after 5 seconds. So our number processing is interrupted. 

The use-case is to finish the number processing even after the source stream has ended


```ts
import { Effect, Schedule, Stream } from "effect"

const socket = Stream.fromSchedule(Schedule.spaced("1 second")).pipe(
  Stream.take(5)
)

const processNumber = (num: number) => Effect.sleep("1 hour")

const program = socket.pipe(
  Stream.flatMap((num) => Stream.scoped(Effect.forkScoped(processNumber(num))).pipe(Stream.as(num))),
  Stream.runDrain
)

Effect.runPromise(program).then((x) => console.log("program finished"), () => console.log("error"))
```

**Comment by mikearnaldi** [comment] 2024-07-06 15:44
> This code finishes after 5 seconds. So our number processing is interrupted.
> 
> The use-case is to finish the number processing even after the source stream has ended
> 
> ```ts
> import { Effect, Schedule, Stream } from "effect"
> 
> const socket = Stream.fromSchedule(Schedule.spaced("1 second")).pipe(
>   Stream.take(5)
> )
> 
> const processNumber = (num: number) => Effect.sleep("1 hour")
> 
> const program = socket.pipe(
>   Stream.flatMap((num) => Stream.scoped(Effect.forkScoped(processNumber(num))).pipe(Stream.as(num))),
>   Stream.runDrain
> )
> 
> Effect.runPromise(program).then((x) => console.log("program finished"), () => console.log("error"))
> ```

that's because the stream ends, a value is returned, if you want that behaviour you should not exit and join the forked fiber

**Comment by dilame** [comment] 2024-07-06 15:45
The code with `while(yield* peel)` is very beautiful and impressive BTW 😃 
But it also interrupts number processing

```ts
import { Chunk, Effect, Schedule, Sink, Stream } from "effect"

const socket = Stream.fromSchedule(Schedule.spaced("1 second")).pipe(
  Stream.take(5)
)
const processNumber = (num: number) => Effect.sleep("1 hour")

const stream = socket.pipe(
  Stream.flatMap((num) => Stream.scoped(Effect.forkScoped(processNumber(num))).pipe(Stream.as(num)))
)

const program = Effect.gen(function*() {
  let next = stream
  let elements: Chunk.Chunk<Stream.Stream.Success<typeof next>>

  while ([elements, next] = yield* Stream.peel(next, Sink.collectAllN(1)), Chunk.isNonEmpty(elements)) {
    yield* Effect.log(`elements: ${Chunk.toArray(elements)}`)
  }
})

Effect.runPromise(Effect.scoped(program)).then(() => console.log('FINISH))
```

**Comment by mikearnaldi** [comment] 2024-07-06 15:50
yes, that's because the stream ends as explained above. If you want deeper control where the fiber is forked you can use `forkIn` and manually pass a scope or even a FiberSet:

```ts
import { Chunk, Effect, FiberSet, Sink, Stream } from "effect"

declare const socket: Stream.Stream<number>

const processNumber = (num: number) => Effect.sleep("1 hour")

const stream = (fibers: FiberSet.FiberSet) =>
  socket.pipe(
    Stream.tap((num) => FiberSet.run(fibers)(processNumber(num)))
  )

const program = Effect.gen(function*() {
  const fibers = yield* FiberSet.make()

  let next = stream(fibers)
  let elements: Chunk.Chunk<Stream.Stream.Success<typeof next>>

  while ([elements, next] = yield* Stream.peel(next, Sink.collectAllN(1)), Chunk.isNonEmpty(elements)) {
    yield* Effect.log(`elements: ${Chunk.toArray(elements)}`)
  }

  yield* FiberSet.join(fibers)
})

Effect.runPromise(Effect.scoped(program))
```

**Comment by dilame** [comment] 2024-07-06 15:51
Here is my working implementation of it, but it requires a `Stream` to contain `Scope` in it's env. 
I am just trying to understand your words that it is incorrect to have `Stream<A, E, Scope>`. I don't understand why, and i also have a use-case and a solution that looks valid to me, that uses `Stream<A, E, Scope>`. What is wrong with Scope in stream?

```ts
import { Console, Effect, Fiber, Schedule, Sink, Stream } from "effect"

const socket = Stream.fromSchedule(Schedule.spaced("1 second")).pipe(
  Stream.tap((x) => Console.log(x)),
  Stream.take(5)
)

const processNumber = (num: number) => Effect.sleep("1 hour")

const program = Effect.gen(function*() {
  const fibers = yield* socket.pipe(
    Stream.flatMap((num) => Effect.forkScoped(processNumber(num))),
    Stream.runScoped(Sink.collectAll())
  )
  yield* Fiber.joinAll(fibers)
})

Effect.runPromise(Effect.scoped(program)).then(() => console.log("finish"))
```

**Comment by mikearnaldi** [comment] 2024-07-06 15:54
> Here is my working implementation of it, but it requires a `Stream` to contain `Scope` in it's env. I am just trying to understand your words that it is incorrect to have `Stream<A, E, Scope>`. I don't understand why, and i also have a use-case and a solution that looks valid to me, that uses `Stream<A, E, Scope>`. What is wrong with Scope in stream?
> 
> ```ts
> import { Console, Effect, Fiber, Schedule, Sink, Stream } from "effect"
> 
> const socket = Stream.fromSchedule(Schedule.spaced("1 second")).pipe(
>   Stream.tap((x) => Console.log(x)),
>   Stream.take(5)
> )
> 
> const processNumber = (num: number) => Effect.sleep("1 hour")
> 
> const program = Effect.gen(function*() {
>   const fibers = yield* socket.pipe(
>     Stream.flatMap((num) => Effect.forkScoped(processNumber(num))),
>     Stream.runScoped(Sink.collectAll())
>   )
>   yield* Fiber.joinAll(fibers)
> })
> 
> Effect.runPromise(Effect.scoped(program)).then(() => console.log("finish"))
> ```

that can be fine, you're keeping the scope open after stream ends, that's what forkScoped does.

**Comment by dilame** [comment] 2024-07-06 15:56
> that can be fine, you're keeping the scope open after stream ends, that's what forkScoped does.

Yes, to me it also looks good. So, in the end of the day – it's ok to have a `Stream<A, E, Scope>`?

**Comment by dilame** [comment] 2024-07-06 15:58
Thanks for the FiberSet example, didn't know about this feature. Looks pretty useful

**Comment by mikearnaldi** [comment] 2024-07-06 15:58
As long as you don't interact with run, would be better to have it separated from the stream scope if it's not related to the lifetime of the stream

**Comment by dilame** [comment] 2024-07-06 18:37
I'm investigating the `Stream` module and seems like now i have a better understanding of what you are talking about. 
I noticed that `Stream.ensuring` is tied to scope, so even if you finished to consume a stream – the ensuring is executed only when the scope closed. I feel like `Stream.ensurig` should return `Stream<A, E, R | Scope>`. What do you think about it?

**Comment by mikearnaldi** [comment] 2024-07-06 18:39
Given that a Scope is always present you don't really need to track it further, kind of like Layer, that said it might be something we evaluate for 4.0

**Comment by dilame** [comment] 2024-07-06 19:07
Yes, i feel like this is the part that could (_should_?) be redesigned in the next major. 

This behavior contradicts the design of `Effect`, which always explicitly requires `Scope`. Additionally, the naming of `Stream.ensuring` contradicts `Effect.ensuring`. `Stream.ensuring` is internally tied to `Scope`, while `Effect.ensuring` is not, meaning `Effect.ensuring` will always execute immediately after the given effect completes. We also have `Effect.addFinalizer`, which is tied to `Scope` as stated in its type declaration.

```ts
export declare const addFinalizer: <X, R>(
  finalizer: (exit: Exit.Exit<unknown, unknown>) => Effect<X, never, R>
) => Effect<void, never, Scope.Scope | R>
```

`Stream` contradicts the main type of the library – `Effect`. What is called `ensuring` in Stream should be called `addFinalizer` and also require `Scope` in the result type.

As a user, it's important for me to see in the type declarations that some of my stream-constructing modules depend on `Scope`.

For example, somewhere in the third-party library, there might be a declaration like:

```ts
function createWS(): Stream.Stream<number, never, never> {
  return createWebSocketStream().pipe(
    Stream.ensuring(killWebSocket())
  )
}
```

And a user of this library calls `createWS` and sees `Stream.Stream<number, never, never>`, thinking there are no finalizers. They might run this stream in a broader `Scope`, expecting the connection to close when the stream stops consuming.

However, if the result of `createWS` was  `Stream.Stream<number, never, Scope>`, I as a user would already consider managing this Scope more carefully.

Effect is already perhaps the most complex library in the entire TypeScript ecosystem. I've never experienced such a mental load as now when I started working with it. I believe that such nuances should be carefully tracked at the type level to prevent users from making mistakes in an already complex architecture.

**Comment by mikearnaldi** [comment] 2024-07-07 11:31
> Yes, i feel like this is the part that could (_should_?) be redesigned in the next major.
> 
> This behavior contradicts the design of `Effect`, which always explicitly requires `Scope`. Additionally, the naming of `Stream.ensuring` contradicts `Effect.ensuring`. `Stream.ensuring` is internally tied to `Scope`, while `Effect.ensuring` is not, meaning `Effect.ensuring` will always execute immediately after the given effect completes. We also have `Effect.addFinalizer`, which is tied to `Scope` as stated in its type declaration.
> 
> ```ts
> export declare const addFinalizer: <X, R>(
>   finalizer: (exit: Exit.Exit<unknown, unknown>) => Effect<X, never, R>
> ) => Effect<void, never, Scope.Scope | R>
> ```
> 
> `Stream` contradicts the main type of the library – `Effect`. What is called `ensuring` in Stream should be called `addFinalizer` and also require `Scope` in the result type.
> 
> As a user, it's important for me to see in the type declarations that some of my stream-constructing modules depend on `Scope`.
> 
> For example, somewhere in the third-party library, there might be a declaration like:
> 
> ```ts
> function createWS(): Stream.Stream<number, never, never> {
>   return createWebSocketStream().pipe(
>     Stream.ensuring(killWebSocket())
>   )
> }
> ```
> 
> And a user of this library calls `createWS` and sees `Stream.Stream<number, never, never>`, thinking there are no finalizers. They might run this stream in a broader `Scope`, expecting the connection to close when the stream stops consuming.
> 
> However, if the result of `createWS` was `Stream.Stream<number, never, Scope>`, I as a user would already consider managing this Scope more carefully.
> 
> Effect is already perhaps the most complex library in the entire TypeScript ecosystem. I've never experienced such a mental load as now when I started working with it. I believe that such nuances should be carefully tracked at the type level to prevent users from making mistakes in an already complex architecture.

the issue is interaction with stuff like peeling, which assumes an embedded Scope, the key difference with effect is Stream is multi-shot. Maybe a strategy like Layer where the Layer has a default Scope but doesn't prevent you from also having an explicit one

**Comment by datner** [comment] 2024-07-13 04:09
@dilame I'm closing this issue as resolved

**Closed by datner** 2024-07-13 04:09 UTC
Labels: working as intended
