### ISSUE TITLE
Effect Schema: ArrayFormatter fails to get array item error when min/max length are defined

### ISSUE THREAD

**Issue by canastro** [Effect-TS/effect#2599] opened 2024-04-22 16:34 UTC
### What version of Effect is running?

3.0.3

### What steps can reproduce the bug?

Given the following schema:
```ts
const Schema = S.Struct({
  outcomes: pipe(
    S.Array(
      S.Struct({
        id: S.String,
        text: pipe(
          S.String,
          S.message(() => 'common.error_invalid_outcome_type'),
          S.minLength(1, { message: () => 'common.error_required_field' }),
          S.maxLength(50, { message: () => 'common.error_max_length_field' })
        ),
      })
    ),
    // If you uncomment this line, the test passes
    S.minItems(1, { message: () => 'common.error_min_length_field' })
  ),
});
```

If you run 
```ts
const result = pipe(
    {
      outcomes: [
        { id: '1', text: '' },
        { id: '2', text: 'this one is valid' },
        { id: '3', text: '1234567890'.repeat(6) },
      ],
    },
    S.decodeUnknown(Schema),
    Effect.catchTag('ParseError', (error) => ArrayFormatter.formatError(error)),
    Effect.tap((result) => Effect.log(result)),
    Effect.runSync
  );

console.log(result);
```

See stackblitz: https://stackblitz.com/edit/node-i8ixxo?file=package.json,test/basic.test.ts,README.md

### What is the expected behavior?

I expect the code above to return:

```ts
{
      _tag: 'Refinement',
      path: ['outcomes', 0, 'text'],
      message: 'common.error_required_field',
}
```

### What do you see instead?

Instead it returns:

```ts
[
    {
      _tag: "Refinement",
      message: "common.error_min_length_field",
      path: ["outcomes"],
    },
  ]
```

Which is wrong as the outcome's array has more than 1 item.

### Additional information

If you comment the line `    S.minItems(1, { message: () => 'common.error_min_length_field' })` then you would get the desired output.

**Comment by gcanti** [comment] 2024-04-26 16:16
The behavior is as intended, meaning that when setting a custom message, it takes precedence over everything else (see https://github.com/Effect-TS/effect/blob/main/packages/schema/README.md#custom-error-messages). However, upon reflection, I realize that this logic may work well for scalar value refinements but not for a case like this, where we refine a more complex data structure (such as an array of a struct). Therefore, I'm considering refactoring the message logic in the next minor version of the schema so that the high precedence of the message is opt-in.

In short, the logic could be as follows, given a filter:
- If there is a custom message defined on it:
  - If this message is marked as `override: true`, then this message is used unless the error concerns a previous refinement and that refinement has a custom message, in which case the message of that previous refinement is calculated.
  - If the message is NOT marked with `override: true`:
    - If the error concerns this refinement and not a previous one, its custom message is used.
    - Otherwise, if the error concerns a previous refinement, the corresponding message is calculated.
- Otherwise, the default message is calculated.

**Comment by canastro** [comment] 2024-04-27 13:51
Just to give more details on my usage as this might be a common use-case.

I have a form which contains a list of items. This list needs to have at least one item. Each item needs to be a string with length > 1 and < 50.
I want to be able to show an error next to the input that is currently invalid.

It would be awkward for the user to start writing their 3rd item in the list, somehow make that item invalid and have an error saying that the list does not have at least 1 item.

I really can't understand how the expected behaviour could be to show a minLength error on an array that has 3 items.

**Comment by gcanti** [comment] 2024-04-27 14:32
I agree that the current behavior is not good.

It's the "expected behavior" given how the messaging system *currently works*, not in the sense that it's correct overall and especially not in your case: as I wrote above, the current behavior would work fine for refinements of scalar values (such as `string` or `number`) but not for refinements of more complex data structures like the case you presented (a refinement of an array of structs).

So the behavior encoded in the formatter needs to be refactored to improve it, which is exactly what I'm doing right now by working on the development branch of the next minor https://github.com/Effect-TS/effect/pull/2634

**Comment by canastro** [comment] 2024-04-27 14:39
Awesome, thank you for the quick feedback.

**Closed** 2024-05-10 16:27 UTC
Labels: enhancement, schema, Fix Available
