### ISSUE TITLE
TaggedEnum.WithGenerics does not have $is and $match helpers

### ISSUE THREAD

**Issue by danielo515** [Effect-TS/effect#2767] opened 2024-05-17 11:47 UTC
### What version of Effect is running?

3.4.0

### What steps can reproduce the bug?

```ts
import { Data } from "effect";
type RemoteData<Success, Failure> = Data.TaggedEnum<{
  Loading: {};
  Success: { data: Success };
  Failure: { reason: Failure };
}>;
interface RemoteDataDefinition extends Data.TaggedEnum.WithGenerics<2> {
  readonly taggedEnum: RemoteData<this["A"], this["B"]>;
}
const { Loading, Failure, Success, $is, $match } = Data.taggedEnum<RemoteDataDefinition>();

```

### What is the expected behavior?

I expect to have the same utility functions as that TaggedEnum has

### Additional information

I have to do my own helper methods like this:

```ts
import { Data } from "effect";
type RemoteData<Success, Failure> = Data.TaggedEnum<{
  Loading: {};
  Success: { data: Success };
  Failure: { reason: Failure };
}>;
interface RemoteDataDefinition extends Data.TaggedEnum.WithGenerics<2> {
  readonly taggedEnum: RemoteData<this["A"], this["B"]>;
}
const { Loading, Failure, Success } = Data.taggedEnum<RemoteDataDefinition>();
export function of<T>(data: T) {
  return Success<T, never>({ data });
}

type Loading<A, E> = Extract<RemoteData<A, E>, { _tag: "Loading" }>;
type Success<A, E> = Extract<RemoteData<A, E>, { _tag: "Success" }>;

export function isLoading<A, E>(self: RemoteData<A, E>): self is Loading<A, E> {
  return self._tag === "Loading";
}

export function isSuccess<A, E>(self: RemoteData<A, E>): self is Success<A, E> {
  return self._tag === "Success";
}

export function map<A, E, B>(cb: (self: RemoteData<A, E>) => B) {
  return (self: RemoteData<A, E>) => {
    if (isSuccess(self)) {
      return Success({ data: cb(self.data) });
    }
    return self;
  };
}

```

**Comment by mikearnaldi** [comment] 2024-05-17 11:55
Not a bug, already addressed in https://github.com/Effect-TS/effect/pull/2702

**Closed by mikearnaldi** 2024-05-17 11:55 UTC
Labels: bug
