### ISSUE TITLE
Stream.interruptWhenDeferred doesn't instantly interrupt the stream

### ISSUE THREAD

**Issue by dilame** [Effect-TS/effect#3141] opened 2024-07-02 10:28 UTC
### What version of Effect is running?

3.4.6

### What steps can reproduce the bug?

When using `Stream.interruptWhenDeferred` in conjunction with `Deferred.succeed`, the stream is not interrupted as expected. Instead of the stream being interrupted after the first element, it continues to process all elements. This behavior is contrary to the expected functionality of `Stream.interruptWhenDeferred`.

```ts
import { Deferred, Effect, Stream } from 'effect';
import * as console from 'node:console';

const s1 = Stream.make(1, 2, 3)

const program = Effect.gen(function* () {
  const interrupt = yield* Deferred.make<void>();
  return yield* s1.pipe(
    Stream.tap(() => Deferred.succeed(interrupt, void 0)),
    Stream.interruptWhenDeferred(interrupt),
    Stream.runCollect,
  );
});

Effect.runPromise(program).then(
  (r) => console.log(r),
  (e) => console.error(e),
);
```

### What is the expected behavior?

```js
{ _id: 'Chunk', values: [ 1 ] }
```

### What do you see instead?

```js
{ _id: 'Chunk', values: [ 1, 2, 3 ] }
```

### Additional information

This issue affects the ability to properly interrupt streams using `Deferred`, leading to potential performance and logical errors in applications relying on this behavior.

**Comment by mikearnaldi** [comment] 2024-07-03 17:33
The stream is fully synchronous and there is no chance of interrupting a sync op, if you add a delay it works as expected:

```ts
import { Deferred, Effect, Stream } from "effect"
import * as console from "node:console"

const s1 = Stream.make(1, 2, 3).pipe(
  Stream.tap(() => Effect.sleep("100 millis"))
)

const program = Effect.gen(function*() {
  const interrupt = yield* Deferred.make<void>()
  return yield* s1.pipe(
    Stream.tap(() => Deferred.succeed(interrupt, void 0)),
    Stream.interruptWhenDeferred(interrupt),
    Stream.runCollect
  )
})

Effect.runPromise(program).then(
  (r) => console.log(r),
  (e) => console.error(e)
)
```

**Comment by mikearnaldi** [comment] 2024-07-03 17:35
Similarly if you add a yield with a lower priority than 0:

```ts
import { Deferred, Effect, Stream } from "effect"
import * as console from "node:console"

const s1 = Stream.make(1, 2, 3).pipe(
  Stream.tap(() => Effect.yieldNow({ priority: 1 }))
)

const program = Effect.gen(function*() {
  const interrupt = yield* Deferred.make<void>()
  return yield* s1.pipe(
    Stream.tap(() => Deferred.succeed(interrupt, void 0)),
    Stream.interruptWhenDeferred(interrupt),
    Stream.runCollect
  )
})

Effect.runPromise(program).then(
  (r) => console.log(r),
  (e) => console.error(e)
)
```

**Comment by IMax153** [comment] 2024-07-10 18:36
Going to close this as it's working as intended.

**Closed by IMax153** 2024-07-10 18:36 UTC
Labels: working as intended
